### PR TITLE
Merge footer metadata into the header component

### PR DESCRIPTION
**Pull request by frankieroberto**
This was a quick idea, after doing something similar on the [bat design history](https://github.com/DFE-Digital/bat-design-history/pull/709) - good idea, or not?

---

This removes the "document footer" component, and instead merges its metadata (post date and authors) into the "document header" component.

This is because we've now changed the default post template to include the footer component at the top of the article, after the header.

The semantic difference between the header and footer elements isn't clearly defined, and [the HTML spec says](https://html.spec.whatwg.org/#the-footer-element):

> Footers don't necessarily have to appear at the end of a section, though they usually do.

..so the current behaviour isn't wrong. However it's possibly a bit unexpected?

The HTML spec includes some examples of article publication dates in the [`<header>`](https://html.spec.whatwg.org/#the-header-element) element.

The MDN examples include author and post date within [their header documentation](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/header) too.

Merging the metadata into the header component simplifies our code a little bit, and also potentially allows us to resurrect the document footer component in future for anything we think might usefully appear at the bottom (an edit link to the source for the post on github maybe?)

### CODE REVIEW

**Comment by fofr** [comment]
This change looks good to me.

Any thoughts @paulrobertlloyd?

This would be a breaking change, so would need a major version bump.

**Comment by paulrobertlloyd** [comment]
Yeah, not opposed to this. Bit annoying that we didn’t do this when we last refactored these components, which wasn’t that long ago, but such is life.

Would need a version bump, as have been burnt many times before my not being so careful (which he says, trying hard to let go of the antiquated idea that a major version should include major features, not just breaking changes…)

**Review by paulrobertlloyd — APPROVED** [review]

**Comment by frankieroberto** [comment]
> Bit annoying that we didn’t do this when we last refactored these components, which wasn’t that long ago, but such is life.

That was probably my fault, sorry! 🤦🏻‍♂️

**Comment by paulrobertlloyd** [comment]
> This would be a breaking change, so would need a major version bump.

Oops. That did not happen. 🤦🏼‍♂️

**Pull request merged**
